### ISSUE TITLE
No gear showing up with `plotDataExplorer`

### ISSUE THREAD

**Issue by sfregosi** [TaikiSan21/PAMpal#1]
Hi @TaikiSan21 

I'm trying to use `plotDataExplorer` for the first time and I get an initial plot but no gear icon for modifying it. I ensured I had the `manipulate` package installed and loaded it using `library()` but no luck. I also tried calling the function on the full AcousticStudy and just a single event within an AcousticStudy. My AcousticStudy was created using `mode = 'time'` and grouping according to a csv of encounters. I'm using R version 4.3.0, RStudio version 2023.03.1 Build 446 and PAMpal version 1.0.0

Any other troubleshooting ideas? Thank you!

**Comment by TaikiSan21** [comment]
Ugh, this function has been a headache for a while. When I originally wrote it, the manipulate part would work consistently. But then something changed and I haven't been able to find a consistent work around to get it functioning properly. I've been meaning to remove it from the package and the tutorial website since it's behavior has been unreliable, but I haven't gotten around to it.

I'll add it to my list to try and spend some time trying to fix it, but until then I unfortunately don't have any advice.

**Comment by sfregosi** [comment]
Ha definitely did *not* mean for this to add to any existing headache, just wanted to make sure there wasn't something obvious I was missing. If you were planning on phasing it out, don't worry about fixing on my account. It sounds like a totally awesome feature I should have used it back when it worked :)

**Comment by TaikiSan21** [comment]
This was a long time ago, but FYI this function has now been reworked to run a local Shiny app instead of using the not-very-reliable `manipulate` package, so it works again. As of v 1.2.1 just pushed to GitHub.
